'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class historico_movimientos
    Public Property documento As String
    Public Property nro_cuenta As String
    Public Property id_movimiento As Integer
    Public Property fecha As Date

    Public Overridable Property cuentas As cuentas
    Public Overridable Property movimientos As movimientos
    Public Overridable Property personas As personas

End Class
