'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class movimientos
    Public Property id_movimiento As Integer
    Public Property nombre_mvto As String

    Public Overridable Property historico_movimientos As ICollection(Of historico_movimientos) = New HashSet(Of historico_movimientos)

End Class
