'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class personas
    Public Property primer_nombre As String
    Public Property segundo_nombre As String
    Public Property primer_apellido As String
    Public Property segungo_apellido As String
    Public Property documento As String

    Public Overridable Property cuentas As ICollection(Of cuentas) = New HashSet(Of cuentas)
    Public Overridable Property historico_movimientos As ICollection(Of historico_movimientos) = New HashSet(Of historico_movimientos)

End Class
